### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by aschrijver** [comment]
For binary files we should have a way to know which version of the Markdown document they relate to, and indicate the version in the filename.

The standard documentation format is markdown, because it is common text-only document type, that you can open in any text editor on any platform, and that is displayed with rich formatting on Github and on the forum.

But when having digital documents it becomes hard to judge if they are in sync with the markdown.
I suggest having the 'source of truth' be markdown, and when creating an actual RFP to make a markdown copy in the right location, finalise the text and add links to any binary formats in the same folder that have been created from it.

PS. Binary formats create contribution barriers, but we'll still need them. I do not have Word, but can read `docx` in OpenOffice, but not save while keeping the exact same formatting. We will also have people creating Illustrator, Photoshop and InDesign documents, etc. later on, that need payed software subscriptions. That should be less of a problem, but this is a template, so more important.

**Comment by aschrijver** [comment]
PS. We need to look at the way you created this PR. The branch with the patch should not end up in this repository, but in the fork that you have created (you can see that in the 'Code' tab in the 'branches' dropdown). This relates to the open issue https://github.com/humanetech-community/humanetech-community-awareness/issues/16 so you might describe your procedure there.

**Comment by georgeshk** [comment]
Sorry, I am a bit lost. Please explain what I should have done.

**Comment by georgeshk** [comment]
Ok, now I am confused between "branch" and "fork". When I proposed to add the file, it was under a fork called something like "georges-patch-2". I then submitted a pull request. No idea about branches!

**Comment by georgeshk** [comment]
> The standard documentation format is markdown

Agreed, the idea was not to replace the markdown, or make the binary the "source of truth". This stems from helping @patmatsu approach a videographer, and in the future the Word version will be used by all contributors sending RFPs out.

> For binary files we should have a way to know which version of the Markdown document they relate to, and indicate the version in the filename.

I propose we simply update the Markdown document with a link to the latest binary file that matches it. 

Is there anything you want me to do before you accept this PR?

**Comment by aschrijver** [comment]
> Ok, now I am confused between "branch" and "fork". When I proposed to add the file, it was under a fork called something like "georges-patch-2". I then submitted a pull request. No idea about branches!

I think I know the reason.

- A **fork** creates a local copy of the entire repository under your own Github account

- The **master branch** always reflects the latest status of all content (files and folders) in your project, and for all contributors.

- If you work on something you can create a sepate **named branch** to work in parallel, until you are ready to merge everything with master, after which you can remove your branch.

- Both the original repository and the local forks have brances, and you can create new ones in both.

- Now when pressing _Edit_, the Github UI does this automatically for you.
  - So this branch creation is determined on _where_ you pressed edit: in your fork or original repo (called the **upstream repository**).

You edited in the original, which you can do, because you are a maintainer. For anyone else - contributors - pressing edit will both fork and create a `patch` branch, because they do not have the same write access to the repository as a maintainer has.

Creating the ultimate PR, the request to merge is the same in both cases: You can do this from the fork just as well. Github checks for changes with upstream automatically when you select 'Create pull request'.

This all may sound very complex, but it allows for very complex projects too, where many people work in parallel, yet independently.

No need to change anything in how you work for now. I will take what I just typed above and incorporate in #16 

:+1:

**Comment by aschrijver** [comment]
> I propose we simply update the Markdown document with a link to the latest binary file that matches it.

Agreed. I will close this without merging.

**Pull request closed without merging**
